Refactor analysis base and use paralell streams
PalladioSimulator/Palladio-Addons-DataFlowConfidentiality-Analysis pull request #52
Opened 2023-04-12 15:57 UTC by Entenwilli

This PR refactors the base of the analysis and aims to improve performance by using parallel streams.

This PR closes #50 and #51

2023-05-08 07:23 UTC, sebinside commented
How is the state of this PR? Ready to be reviewed?

2023-05-10 11:47 UTC, sebinside requested changes
First of all: This is a massive pull request with many changes to the internal analysis structure and how it is created and used. Thank you for this work, it really looks like a lot of effort.

I did not test the analysis yet, this review only contains static comments to the code. Some comments can easily be resolved in the final PR version, others should be discussed first. All in all, the refactored version should be finally what we imagined of a usable data flow analysis and I would argue that the current version of your PR is already 90% there.

2023-05-10 11:47 UTC, sebinside commented on bundles/org.palladiosimulator.dataflow.confidentiality.analysis/src/org/palladiosimulator/dataflow/confidentiality/analysis/characteristics/node/PCMNodeCharacteristicsCalculatorImpl.java
> +public class PCMNodeCharacteristicsCalculatorImpl implements NodeCharacteristicsCalculator {
Naming: Remove `Impl`

2023-05-10 11:47 UTC, sebinside commented on bundles/org.palladiosimulator.dataflow.confidentiality.analysis/src/org/palladiosimulator/dataflow/confidentiality/analysis/characteristics/node/PCMNodeCharacteristicsCalculatorImpl.java
> +	public void checkAssignments(Assignments assignments) {
We should discuss the public API of this class. Its super class only required one method, however, several more are public. Are they required outside this class?

2023-05-10 11:47 UTC, sebinside commented on bundles/org.palladiosimulator.dataflow.confidentiality.analysis/src/org/palladiosimulator/dataflow/confidentiality/analysis/characteristics/variable/PCMDataCharacteristicsCalculator.java
> +    		List<CharacteristicValue> nodeCharacteristics,
I don't understand the use of node characteristics in this class, we should discuss this (and the javadoc should reflect the usage of the variable)

2023-05-10 11:47 UTC, sebinside commented on bundles/org.palladiosimulator.dataflow.confidentiality.analysis/src/org/palladiosimulator/dataflow/confidentiality/analysis/characteristics/variable/DataCharacteristicsCalculatorFactory.java
> +public interface DataCharacteristicsCalculatorFactory {
Why is a factory required here while there is no factory required to create the node characteristics calculators?

2023-05-10 11:47 UTC, sebinside commented on bundles/org.palladiosimulator.dataflow.confidentiality.analysis/src/org/palladiosimulator/dataflow/confidentiality/analysis/dsl/AbstractStandalonePCMDataFlowConfidentialityAnalysis.java
> +package org.palladiosimulator.dataflow.confidentiality.analysis.dsl;
I'm not sure about the `dsl` in the package name. I would not see this as a dsl but rather as the analysis core classes

2023-05-10 11:47 UTC, sebinside commented on bundles/org.palladiosimulator.dataflow.confidentiality.analysis/src/org/palladiosimulator/dataflow/confidentiality/analysis/dsl/AbstractStandalonePCMDataFlowConfidentialityAnalysis.java
> +package org.palladiosimulator.dataflow.confidentiality.analysis.dsl;
Besides this, I like the separation in abstract, legacy and normal

2023-05-10 11:47 UTC, sebinside commented on bundles/org.palladiosimulator.dataflow.confidentiality.analysis/src/org/palladiosimulator/dataflow/confidentiality/analysis/dsl/LegacyStandalonePCMDataFlowConfidentialityAnalysis.java
> +	public LegacyStandalonePCMDataFlowConfidentialityAnalysis(PCMAnalysisBuilderData builderData, AnalysisData analysisData) {
The javadoc does not match the constructor

2023-05-10 12:50 UTC, sebinside commented on bundles/org.palladiosimulator.dataflow.confidentiality.analysis/src/org/palladiosimulator/dataflow/confidentiality/analysis/builder/pcm/PCMDataFlowConfidentialityAnalysisBuilder.java
> +			return new LegacyStandalonePCMDataFlowConfidentialityAnalysis(builderData, builderData.createAnalysisData());
-> As discussed, an analysis should know nothing about its builder's data

2023-05-10 13:01 UTC, sebinside commented on bundles/org.palladiosimulator.dataflow.confidentiality.analysis/src/org/palladiosimulator/dataflow/confidentiality/analysis/characteristics/variable/PCMDataCharacteristicsCalculator.java
> +    		List<CharacteristicValue> nodeCharacteristics,
Document that this is because of `.container`

2023-05-11 08:10 UTC, Entenwilli commented on README.md
> +This repository contains an analysis to extract dataflows from a palladio modelling project,
I've configured my editor to format like the plugin you linked, so for future changes it should be fine

2023-05-11 09:13 UTC, Entenwilli commented
I've addressed the requested changes and added support for loading resources directly. Now the branch should be ready. @sebinside 

Plan for future versions:
- Validation of analysis data: Assignments and resource loading

2023-05-15 12:31 UTC, merged